server:
  port: 8901
  
spring:
  application:
    name: forest-search-server

#---------------consul-------------------------
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
                      # 启用服务发现
        enabled: true
                      # 是否注册服务
        register: true
                      # 服务停止时取消注册
        deregister: true
                      # 注册到consul的服务名称
        service-name: ${spring.application.name}
                      # 表示注册时使用IP而不是hostname
        prefer-ip-address: true
                      # 执行监控检查的频率
        health-check-interval: 30s
                      # 设置健康检查失败多长时间后，取消注册
        health-check-critical-timeout: 30s
                      # 健康检查的路径
        health-check-path: /actuator/health
                      # 服务注册标识，格式为：应用名称+服务器IP+端口
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

  es:
    host: localhost
    port: 9300
    clusterName: elasticsearch
    enable: true
      
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'



    




      
      

      
      
      
      
      
      
      
      
      
      
      
      
      
      
      