server:  port: 8401
spring:  application:    name: forest-admin
#---------------consul-------------------------  cloud:    config:      enabled: false    consul:      host: localhost      port: 8500      discovery:        tags: management.context-path=/foo, health.path=/ping, user.name=admin, user.password=123456  boot:    admin:      discovery:        ignored-services: consul  security:    user:      name: "admin"      password: "123456"management:  endpoints:    web:      exposure:        include: "*"      path-mapping:        health: /ping      base-path: /foo  endpoint:    health:      show-details: ALWAYS
  


