server:
  port: 8310

spring:
  application:
    name: forest-system-server
  datasource:
           #是否开启读写分离 false 不开启，true 开启
    r-w-separation: false
    names: slave1
    master:      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/complex-system
      username: root
      password: root
      druid:        initial-size: 1
        max-active: 20
    slave1:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/complex-system-cluster
      username: root
      password: root
      druid:
        initial-size: 1
        max-active: 20

#---------------consul-------------------------
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
                      # 启用服务发现
        enabled: true
                      # 是否注册服务
        register: true
                      # 服务停止时取消注册
        deregister: true
                      # 注册到consul的服务名称
        service-name: ${spring.application.name}
                      # 表示注册时使用IP而不是hostname
        prefer-ip-address: true
                      # 执行监控检查的频率
        health-check-interval: 30s
                      # 设置健康检查失败多长时间后，取消注册
        health-check-critical-timeout: 30s
                      # 健康检查的路径
        health-check-path: /actuator/health
                      # 服务注册标识，格式为：应用名称+服务器IP+端口
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'


mybatis-plus:
  mapper-locations: cn/forest/system/mapper/xml/*.xml
  type-aliases-package: www.forest.system.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql


    




      
      

      
      
      
      
      
      
      
      
      
      
      
      
      
      
      