server:
  port: 8301
  
eureka:
  instance:
    prefer-ip-address: true
    instance-id: 192.168.1.111:${server.port}
  client:
    service-url:
      defaultZone: http://192.168.1.111:5555/eureka/
      
spring:
  application:
    name: forest-system-server
  datasource:    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/complex-system
    username: root
    password: root
    druid:      initial-size: 1
      max-active: 20


mybatis-plus:
  mapper-locations: cn/forest/system/mapper/xml/*.xml
  type-aliases-package: www.forest.system.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql


    




      
      

      
      
      
      
      
      
      
      
      
      
      
      
      
      
      